_prefs: 
  mapid: carnegiecomms.0de7b5ba
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -94.3066
  - 47.4578
  - 4
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 14
minzoom: 0
name: OCI 2017
source: "mapbox:///carnegiecomms.dvwvyuzc"
styles: 
  - style.mss
template: ''
